name: Autograding Tests
on:
- push
- workflow_dispatch

permissions:
  contents: read
  statuses: write

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: (github.event_name != 'push' || github.event.head_commit.message != 'Initial commit')
    env:
      CI: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Disable man-db auto-update (prevents apt-get hangs)
      run: sudo rm -f /var/lib/man-db/auto-update

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: 'lts/*'

    - name: Install dependencies using the devcontainer setup script
      run: ./.devcontainer/postCreate.sh
      timeout-minutes: 5

    - name: Run the example suite using autograder
      uses: ohjelmistokehitys/autograder@v0
      timeout-minutes: 3
      with:
        test_suite: ./.grading/config.json

    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 7
