name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    env:
      CI: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
      timeout-minutes: 2
    - name: Install Chromium browser
      run: npx playwright install chromium --with-deps
      timeout-minutes: 2
    - name: Run tests
      run: npx playwright test --reporter="list,html" --project=chromium --trace=on --retries=0
      timeout-minutes: 3
      continue-on-error: true

    - name: Extract traces
      run: "./.github/extract_traces.sh"

    - name: Access the legacy cars table
      id: access-legacy
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Access the legacy cars table
        setup-command: ''
        command: "./.github/find_trace.sh 'Final_CarSheet_v5_(ignore_others).xls'"
        timeout: 1
        max-score: 10

    - name: Open details of a car
      id: open-details
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Open details of a car
        setup-command: ''
        command: "./.github/find_trace.sh 'DeLorean_DMC-12.xls'"
        timeout: 1
        max-score: 10

    - name: Switch to usage tab on car details
      id: switch-tabs
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Switch to usage tab on car details
        setup-command: ''
        command: "./.github/find_trace.sh 'Fuel type'"
        timeout: 1
        max-score: 10

    - name: Access the target system
      id: access-target
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Access the target system
        setup-command: ''
        command: "./.github/find_trace.sh 'Car registry 2.0'"
        timeout: 1
        max-score: 10

    - name: Add a single car successfully
      id: add-car
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Add a single car successfully
        setup-command: ''
        command: "./.github/find_trace.sh 'added successfully!'"
        timeout: 1
        max-score: 10

    - name: Add the rest of the cars successfully
      id: add-all-cars
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Add the rest of the cars successfully
        setup-command: ''
        command: "./.github/find_trace.sh 'You have completed the exercise!'"
        timeout: 1
        max-score: 50


    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ACCESS-LEGACY_RESULTS: "${{steps.access-legacy.outputs.result}}"
        OPEN-DETAILS_RESULTS: "${{steps.open-details.outputs.result}}"
        SWITCH-TABS_RESULTS: "${{steps.switch-tabs.outputs.result}}"
        ACCESS-TARGET_RESULTS: "${{steps.access-target.outputs.result}}"
        ADD-CAR_RESULTS: "${{steps.add-car.outputs.result}}"
        ADD-ALL-CARS_RESULTS: "${{steps.add-all-cars.outputs.result}}"

      with:
        runners: access-legacy,open-details,switch-tabs,access-target,add-car,add-all-cars

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 3
